name: PR
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    timeout-minutes: 6
    defaults:
      run:
        shell: bash -ex -o pipefail {0}
        working-directory: ./src/github.com/${{ github.repository }}
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
      - name: Fetch tags
        run: |
          git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      # FIXME: builds will be more reliable with docker auth
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        timeout-minutes: 2
        run: |
          make gen
          make check-fmt
          make vendor
          git diff --exit-code
      - name: Test
        timeout-minutes: 2
        run: |
          make test
